USE [master]
GO

/****** Object:  Database [MWC_CustomOrder]    Script Date: 8/21/2022 7:22:03 PM ******/
CREATE DATABASE [MWC_CustomOrder]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MWC_CustomOrder].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MWC_CustomOrder] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET ARITHABORT OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MWC_CustomOrder] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MWC_CustomOrder] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MWC_CustomOrder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MWC_CustomOrder] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET RECOVERY FULL 
GO

ALTER DATABASE [MWC_CustomOrder] SET  MULTI_USER 
GO

ALTER DATABASE [MWC_CustomOrder] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MWC_CustomOrder] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MWC_CustomOrder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MWC_CustomOrder] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MWC_CustomOrder] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MWC_CustomOrder] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MWC_CustomOrder] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MWC_CustomOrder] SET  READ_WRITE 
GO


